version: '3.8'

services:
  bot:
    image: ghcr.io/mauvehed/trackerstatus_discord:main
    container_name: trackerstatus_bot
    volumes:
      - ./config:/app
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped 