version: '3.8'

services:
  bot:
    image: ghcr.io/mauvehed/trackerstatus_discord:main
    container_name: trackerstatus_bot
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped 