version: '3.8'

services:
  bot:
    build: .
    container_name: trackerstatus_bot
    volumes:
      - ./config.json:/app/config.json
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped 