services:
  bot:
    image: ghcr.io/mauvehed/trackerstatus_discord:latest
    container_name: trackerstatus_discord
    volumes:
      - trackerstatus_discord:/app/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped

volumes:
  trackerstatus_discord: 